In [3]:
import numpy as np
import torch_geometric
import torch_geometric.nn as geom_nn
import torch_geometric.data as geom_data

In [18]:
A = [[1,1,1],[2,2,2],[2,2,2]]
B = [[3,3,3],[4,4,4],[2,2,2]]

In [19]:
np.einsum('ij,ji->i', A, B)

array([ 9, 18, 18])

In [20]:
np.dot(A,B)

array([[ 9,  9,  9],
       [18, 18, 18],
       [18, 18, 18]])

In [23]:
DATASET_PATH = './data'
cora_dataset = torch_geometric.datasets.Planetoid(root=DATASET_PATH, name="Cora")

Processing...
Done!


In [26]:
cora_dataset[0]

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [31]:
cora_dataset[0]['train_mask']

tensor([ True,  True,  True,  ..., False, False, False])

In [4]:
DATASET_PATH = './data'
tu_dataset = torch_geometric.datasets.TUDataset(root=DATASET_PATH, name="MUTAG")

print("Data object:", tu_dataset.data)
print("Length:", len(tu_dataset))
print(f"Average label: {tu_dataset.data.y.float().mean().item():4.2f}")



Data object: Data(x=[3371, 7], edge_index=[2, 7442], edge_attr=[7442, 4], y=[188])
Length: 188
Average label: 0.66


Extracting data/MUTAG/MUTAG.zip
Processing...
Done!


In [23]:
vals = []

for graph in tu_dataset:
    vals += [graph.y.item()]

In [25]:
from collections import Counter

Counter(vals)

Counter({1: 125, 0: 63})